

  apt-get update 
  apt-get install python3 python3-pip -y 
  python3 --version 
  python3 -m pip --version 

  python3 -m pip install vtk 

  ## from .vtkWebCore import *
  apt-get  install libx11-dev -y 
  apt-get  install libgl1-mesa-dev 
  apt-get  libxrender-dev -y 


  ## nodejs 16.x  
  apt-get install curl -y
  curl -fsSL https://deb.nodesource.com/setup_16.x | bash -

  apt-get -y install nodejs -y
  node  -v # v16.15.0 
